### ISSUE TITLE
Signing Certificate

### ISSUE THREAD

**Issue by ctgroupgit** [ministero-salute/dcc-utils#2]
# Issue content
I would now if the file signing_certificate.crt is generic for check all Green Pass or needed a specific one.

Thanks.

**Comment by ctgroupgit** [comment]
HI @astagi,

thanks for reply,
I tried the script you recommended but when I try to scan a Valid Green Pass, I always get the same error:

Error: Signature missmatch
    at /node_modules/cose-js/lib/sign.js:152:15
    at new ZoneAwarePromise (http://localhost:4300/polyfills.js:1728:23)
    at doVerify (/node_modules/cose-js/lib/sign.js:131:10)
    at /node_modules/cose-js/lib/sign.js:251:16
    at ZoneDelegate.invoke (http://localhost:4300/polyfills.js:555:160)
    at Zone.run (http://localhost:4300/polyfills.js:281:37)
    at http://localhost:4300/polyfills.js:1701:28
    at ZoneDelegate.invokeTask (http://localhost:4300/polyfills.js:588:173)
    at Zone.runTask (http://localhost:4300/polyfills.js:338:39)
    at drainMicroTaskQueue (http://localhost:4300/polyfills.js:804:25)

**Comment by astagi** [comment]
Hi @ctgroupgit , sounds really weird... I substitute the QRCode image path here

```js
  const dcc = await DCC.fromImage('./data/Green_Pass_Valid.png');
```

then after launching the script, I get my payload. 

```js
{
  v: [
    {
      dn: 1,
      ma: '...',
      vp: '...',
      dt: '....',
      co: 'IT',
      ci: '....',
      mp: 'EU/1/20/1528',
      is: 'Ministero della Salute',
      sd: 2,
      tg: '...'
    }
  ],
  nam: { ... },
  ver: '1.0.0',
  dob: '...'
}
```

The script shouldn't throw any exception, everything is wrapped by a "catch'em all" try except block.
